version: "3"

services:
  frontend:
    build:
      context: ./service
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    ports:
      - 3000:3000
    restart: always
    command: yarn start